language: go

services:
  - postgresql

go:
  - master

before_script:
  - psql -c "CREATE DATABASE rfcs;" -U postgres
  - psql -c "CREATE USER rrfc WITH PASSWORD 'password123';" -U postgres

script:
    - go test -v
