# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: ${PGDATA}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /data:/data
    networks:
      - rfcnet
    deploy:
      restart_policy:
        condition: on-failure

  rrfc:
    image: skarlso/rrfc:latest
    ports:
      - 443:443
    networks:
      - rfcnet
    environment:
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DBNAME: ${PG_DBNAME}
      PG_USER: ${PG_USER}
      PG_SSLMODE: ${PG_SSLMODE}
      PG_HOST: db
      PG_PORT: 5432
      SITE_LOCATION: site
      LIST_URL: "https://www.ietf.org/download/rfc-index.txt"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
networks:
  rfcnet:
